### ISSUE TITLE
generic-oidc authentication problems

### ISSUE THREAD

**Issue by inghamn** [seattle-uat/civiform#2829] opened 2022-06-30 12:44 UTC
I am having trouble getting the generic-oidc authentication working for applicants.   To test it, I have set up a Application Group for civiform applicants on our ADFS server.

I am able to get civiform to start up cleanly; however, I am unable to get authentication working, at all.  When attempting the applicant authentication, I get errors like "invalid token" and "client not authorized".

It looks like the oidc library is not able to validate the token when the user arrives back from ADFS.  Without that, the library is not able to pull the email address out of the token.

I have tried varying the RESPONSE_MODE and RESPONSE_TYPE.  I think I am shooting for configuring civiform to do Implicit Flow against our ADFS server.  (I have implemented this flow in other web applications against our ADFS).

The config from my latest attempt is:

```
CIVIFORM_APPLICANT_IDP:       'generic-oidc'
APPLICANT_AUTH_PROVIDER:      'generic-oidc'
APPLICANT_AUTH_PROTOCOL:      'OIDC'
APPLICANT_OIDC_PROVIDER_NAME: 'cob_adfs'
APPLICANT_OIDC_CLIENT_ID:     'xxxxxxxxx'
APPLICANT_OIDC_CLIENT_SECRET: 'xxxxxxxxx'
APPLICANT_OIDC_DISCOVERY_URI: 'https://auth.bloomington.in.gov/adfs/.well-known/openid-configuration'

# Optional arguments to configure - shown are the default values
APPLICANT_OIDC_RESPONSE_MODE:     'query'
APPLICANT_OIDC_RESPONSE_TYPE:     'code'
APPLICANT_OIDC_ADDITIONAL_SCOPES: ''
# APPLICANT_OIDC_LOCALE_ATTRIBUTE:  '' # (for language codes, like 'en' or 'sp', if your provider has that selector)
# APPLICANT_OIDC_EMAIL_ATTRIBUTE:   'email'

# And for customizing the name, any number of the following (they'll stay in order).
# If using the default oidc display_name, only override the first name.
# APPLICANT_OIDC_FIRST_NAME_ATTRIBUTE:  'name'
# APPLICANT_OIDC_MIDDLE_NAME_ATTRIBUTE: ''
# APPLICANT_OIDC_LAST_NAME_ATTRIBUTE:   ''
```

I've attached the log from civiform
[out.log](https://github.com/seattle-uat/civiform/files/9019838/out.log)

**Comment by kmcnellis** [comment] 2022-06-30 20:20
According to what I've read, ADFS might need the additional scope "allatclaims" (`The allatclaims scope allows the application to request claims in access token to be added in the ID Token as well.`) to retrieve the user's email. https://docs.microsoft.com/en-us/windows-server/identity/ad-fs/development/ad-fs-openid-connect-oauth-concepts#scopes

The error you are getting in the logs "play.api.UnexpectedException: Unexpected exception[CompletionException: auth.oidc.InvalidOidcProfileException: Unable to get email from profile.]" is saying that the returned JWT doesn't contain the field specified by "APPLICANT_OIDC_EMAIL_ATTRIBUTE" (`email` is the default)

Also, note if you use it, whatever you put in the field "APPLICANT_OIDC_PROVIDER_NAME" gets appended to the callback url (in this case, "/callback/cob_adfs").

**Comment by inghamn** [comment] 2022-06-30 20:46
Just to be sure, I've updated the config to make sure to request allatclaims (ADFS should send it anyway).  Also, I updated the EMAIL_ATTRIBUTE to match what ADFS should send back.

The problem is really starting at the token validation, though.  An invalid token won't have the fields, or at least pac4j won't look for the fields in an invalid token?

```
CIVIFORM_APPLICANT_IDP:       'generic-oidc'
APPLICANT_AUTH_PROVIDER:      'generic-oidc'
APPLICANT_AUTH_PROTOCOL:      'OIDC'
APPLICANT_OIDC_PROVIDER_NAME: 'cob_adfs'
APPLICANT_OIDC_CLIENT_ID:     '051621fc-5ae6-43d8-b3cc-9dd63a6b68ba'
APPLICANT_OIDC_CLIENT_SECRET: 'xxxxx'
APPLICANT_OIDC_DISCOVERY_URI: 'https://auth.bloomington.in.gov/adfs/.well-known/openid-configuration'

# Optional arguments to configure - shown are the default values
APPLICANT_OIDC_RESPONSE_MODE:     'query'
APPLICANT_OIDC_RESPONSE_TYPE:     'code'
APPLICANT_OIDC_ADDITIONAL_SCOPES: 'allatclaims'
# APPLICANT_OIDC_LOCALE_ATTRIBUTE:  '' # (for language codes, like 'en' or 'sp', if your provider has that selector)
APPLICANT_OIDC_EMAIL_ATTRIBUTE:   'upn'
```

![server](https://user-images.githubusercontent.com/630282/176775122-4ae3aa62-4801-4039-95b2-ea59922ac628.png)
![properties](https://user-images.githubusercontent.com/630282/176775124-efd13cb7-cb3f-4a8a-b24e-a5673acb491e.png)
![web_api](https://user-images.githubusercontent.com/630282/176775121-a5ad0e63-223c-48f6-8f87-8af3a35b19d6.png)
![permissions](https://user-images.githubusercontent.com/630282/176775126-10f3c317-6336-416a-9588-4524717e7c08.png)

**Comment by kmcnellis** [comment] 2022-07-01 15:12
The error in your log `play.api.UnexpectedException: Unexpected exception[CompletionException: auth.oidc.InvalidOidcProfileException: Unable to get email from profile.]` is one that we throw, when we attempt to get the email from the returned auth token.   The `InvalidOidcProfileException` is just an internal civiform name, not a pac4j exception.

Was there some other error that led you to think that the returned token was invalid?

**Comment by inghamn** [comment] 2022-07-01 15:47
I don't know if ADFS is going to allow implicit flow using RESPONSE_TYPE of token.  For the other web applications I've implemented OIDC against ADFS, I had to use RESPONSE_TYPE of code.

```
https://auth.bloomington.in.gov/adfs/oauth2/authorize/?
  scope=openid profile email allatclaims
 &response_mode=form_post
 &response_type=id_token token
 &redirect_uri=https://civiform.bloomington.in.gov/callback/cob_adfs
 &nonce=obZs_VDWNM9mb9aegu49x4JyuPdrtc4jEvcTTw4MKQ8
 &client_id=051621fc-5ae6-43d8-b3cc-9dd63a6b68ba
```

ADFS throws this error:
Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthAuthorizationUnauthorizedClientException: MSIS9358: Received invalid OAuth authorization request. The authorization server does not support the response type 'token' for confidential clients.

In my other testing, doing OIDC Implicit Flow authentication with ADFS required me to use:

```
https://auth.bloomington.in.gov/adfs/oauth2/authorize/?
   response_type=code
  &redirect_uri=https://drifter.bloomington.in.gov/blossom/login/oidc
  &client_id=5d941ef5-fd23-43bc-ae29-8fbc638df72d
  &nonce=01787ca6558f399d0df3b1f5afd7fd55&state=22b2a444c9d45beec87d9ea80b9d7064
  &scope=openid allatclaims profile
```  
  
response_mode is "query", by default, I think.  I don't think that's impacting anything here, though.

This is all just to do testing against our ADFS server, of course.  I'll probably have to make allowances for Access Indiana's implementation when we try pointing there.

**Comment by kmcnellis** [comment] 2022-07-01 16:01
> The error that led me to think the returned token was invalid was:
> 
> [error] o.p.o.p.c.OidcProfileCreator - Bad User Info response, error=invalid_token

Ah, interesting.  It appears that in your log, pac4j attempted to call the [UserInfo Endpoint](https://openid.net/specs/openid-connect-core-1_0.html#UserInfo) and is getting an error from it.  It's a non-fatal error, though, so it continues on to the other error (where it tries to retrieve the email).

For the `code` flow, it requires that secondary exchange with the server, vs the `token` method that directly returns the data. 


In our admin authentication, we were able to get ADFS working by requesting only `id_token`, and then adding `allatclaims` to the additional_scopes list.  This bypasses the whole access token mechanism, and returns the claims inside the id_token instead.   Do you want to try that?

If that doesn't work, I'll send you some information about enabling debug logging in the server to get the full error message returned from ADFS (or you could look in the ADFS logs, if you have access). There is likely some other option that they want set for that secondary request.

**Comment by inghamn** [comment] 2022-07-01 16:46
I am unable to get the REPONSE_TYPE "id_token token" to work.  No error on the ADFS side, but a 401 error in CiviForm.  I've attached the logs.

Is there an easy way to send the contents of the id_token to the log, so I can debug?  I'm guessing Ihad have to update java code and recompile for that, though...

```
  CIVIFORM_APPLICANT_IDP:       'generic-oidc'
  APPLICANT_AUTH_PROVIDER:      'generic-oidc'
  APPLICANT_AUTH_PROTOCOL:      'OIDC'
  APPLICANT_OIDC_PROVIDER_NAME: 'cob_adfs'
  APPLICANT_OIDC_CLIENT_ID:     'b16ea2d0-0281-4e14-b19c-2446d461e383'
  APPLICANT_OIDC_CLIENT_SECRET: 'JIqb-AoV71Nb2NrfxaOto8ZoRED0f7N8q2cIpDMD'
  APPLICANT_OIDC_DISCOVERY_URI: 'https://auth.bloomington.in.gov/adfs/.well-known/openid-configuration'

  # Optional arguments to configure - shown are the default values
  APPLICANT_OIDC_RESPONSE_MODE:     'form_post'
  APPLICANT_OIDC_RESPONSE_TYPE:     'id_token token'
  APPLICANT_OIDC_ADDITIONAL_SCOPES: 'allatclaims profile'
  # APPLICANT_OIDC_LOCALE_ATTRIBUTE:  '' # (for language codes, like 'en' or 'sp', if your provider has that selector)
  APPLICANT_OIDC_EMAIL_ATTRIBUTE:   'upn'

```

[out.log](https://github.com/seattle-uat/civiform/files/9030446/out.log)

**Comment by kmcnellis** [comment] 2022-07-06 15:44
I can work getting on a debug build for you.  These problems do seem like they are ADFS-specific.  The 401 error looks like it might be because pac4j doesn't follow redirects in the auth response, and adfs uses those for unauthorized requests.

Have you tried `APPLICANT_OIDC_RESPONSE_TYPE:     'id_token'` (no `token` in there)?

**Comment by inghamn** [comment] 2022-07-06 16:14
I did a test just now with a RESPONSE_TYPE of only 'id_token'.   When ADFS sends the browser back to civiform (using a post), civiform thows a 500 error in the browser, and the server logs a 400 error.

[out.log](https://github.com/seattle-uat/civiform/files/9056450/out.log)

**Comment by inghamn** [comment] 2022-07-06 16:19
Because I keep using the "latest" tag, I also picked up the new image.  This new image is now sending an invalid redirect_uri to ADFS.  It is using localhost, instead of the configured BASE_URL.

Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthInvalidClientRedirectUriException: MSIS9224: Received invalid OAuth authorization request. The received 'redirect_uri' parameter is not a valid registered redirect URI for the client identifier: 'b16ea2d0-0281-4e14-b19c-2446d461e383'. Received redirect_uri: 'http://localhost:9000/callback/cob_adfs'.

**Comment by kmcnellis** [comment] 2022-07-06 17:26
Hm, for the BASE_URL, I don't think that's changed at all in the past week. It does default to localhost if a BASE_URL environment variable isn't set, though.  Can you verify that's getting set?

**Comment by kmcnellis** [comment] 2022-07-06 17:37
The 400 error specifically is likely caused by that redirect url not being set correctly: https://support.okta.com/help/s/article/400-Bad-Request-when-redirecting-to-the-authorize-endpoint-with-no-error-description?language=en_US

**Comment by inghamn** [comment] 2022-07-06 19:15
I can provide the request and response, but first, it is frightening to me that this token can be decoded by a random website out there.  I'm expecting this id_token to  be encrypted using the client_secret (if I'm understanding correctly).  This is why I've been attempting to set REPONSE_TYPE to 'code' (while still using implict)

I deployed this latest test using SNAPSHOT-53b2d30-1657130244

```
https://auth.bloomington.in.gov/adfs/oauth2/authorize/?
     scope=openid profile email allatclaims
    &response_type=id_token
    &redirect_uri=https://civiform.bloomington.in.gov/callback/cob_adfs
    &nonce=B_a8AxqCA-t9DTrUp7SZ8mrhZpNawFtsngJjT2uFchI
    &client_id=b16ea2d0-0281-4e14-b19c-2446d461e383
    &response_mode=form_post
```
ADFS sends the person's browser back to civiform to POST to:
https://civiform.bloomington.in.gov/callback/cob_adfs  with an id_token in the header that can be decoded at the jwt.io website with the user's info that I'm expecting.

The output log on the civiform looks the same. (400 error)

**Comment by azizova-leyla** [comment] 2022-07-07 21:47
We think one of the issues you're facing is because Civiform doesn't support switching auth providers. You're probably trying to create a duplicated row in accounts table. Can you try clearing out both Accounts and Applicants tables?

`DELETE FROM accounts,applicants;`

I'm assuming you don't have any real data in there yet.

**Comment by azizova-leyla** [comment] 2022-07-13 19:24
Access Indiana is working, so I'll close this issue. Added a separate issue to test ADFS for applicant auth (lower priority).

**Closed by azizova-leyla** 2022-07-13 19:24 UTC
Labels: bug
