### ISSUE TITLE
UAT admin can localize/translate forms & questions

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#211] opened 2021-02-22 22:19 UTC
UAT admin can see a list of languages they can localize forms into on a dedicated tab. Then they can specify localized strings for all questions in the form.

It would look something like this on the question page:
![image](https://user-images.githubusercontent.com/77128518/108777687-31d83680-7532-11eb-9551-69f08121ea1b.png)

**Comment by carolinedanzi** [comment] 2021-05-03 18:08
This seems to be a duplicate of #778, which is nearly ready for story acceptance

**Closed** 2021-05-03 18:40 UTC
Labels: i18n, story
