### ISSUE TITLE
Multiple users tied to temporary IDCS account

### ISSUE THREAD

**Issue by leonwong** [seattle-uat/civiform#1764] opened 2021-12-24 00:42 UTC
**Describe the bug**
From Thor Peterson in Seattle: 

> We’re currently using CiviForm for the Utility Discount Program. A customer is reporting that when he logged into his account, the system displayed another customer’s name, and the Seattle City Light account number of yet another person.
> 
> Obviously, this is really problematic! Can you assist in troubleshooting?
>

**Comment by dkatzz** [comment] 2021-12-28 16:55
Members on the team and I weren't able to reproduce. Thor is going to ask the client for repro steps. With the AWS access I have, I'm unfortunately unable to query the database in staging or prod to find issues with the entries.

I'd like to query the database to see if there are any cases where an account has multiple applicants (which shouldn't be the case based on [this comment](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/models/Account.java#L134) or applicants with the [same email](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/auth/CiviFormProfileAdapter.java#L89), which also shouldn't be possible. I also wonder if there is any weird case with [merging](https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/auth/CiviFormProfileAdapter.java#L96) profile data, but I wouldn't expect the applicant to see a name they are unfamiliar with even in that case.

**Comment by dkatzz** [comment] 2021-12-28 21:43
Update from Elise:
- John Yeung is looking into the issue on the IDCS Oracle side of things.
- We have two known examples of this happening (one on 11/22, the other on 12/23).
- IF a resident is using a shared computer, logins could be stored within the same web browser session. That may not be the case in these examples though.

**Comment by dkatzz** [comment] 2021-12-29 21:15
John searched the IDCS profiles and they are linked correctly there. I'm trying to get the AWS permissions to query the database to get more information about what may be stored incorrectly and causing this.

**Comment by rasmi** [comment] 2021-12-30 19:32
While others investigate -- in case this is an issue related to caching of user session credentials behind some shared proxy, I created a [PR that adds the `no-store` header](https://github.com/seattle-uat/civiform/pull/1767) for completeness on disabling caches. I don't know if this is the root cause, but it can't hurt.

**Comment by dkatzz** [comment] 2022-01-02 21:32
I was able to query the database by following [this](https://github.com/seattle-uat/civiform/wiki/Breaking-glass-on-database). I only found one of the users' emails that was impacted, but this user seemed to be linked correctly across the tables. Ran the following queries:

- SELECT * FROM accounts where lower(email_address) LIKE '%applicantemail%';
- SELECT * FROM applicants where account_id = [id from above];
- SELECT * FROM applications where applicant_id = [id from above];

**Comment by rasmi** [comment] 2022-01-04 16:14
Some more speculation and possible paths towards debugging:

If it is a session caching issue:
 - Could it be at the client/browser level? -- Unlikely, because multiple unrelated browsers saw a common user's name.
 - Could it be at the network/proxy level? -- Unlikely for the same reason.
 - Could it be at the serving infra (CDN/load balancer/application server) level?  -- Possibly, but seemingly unlikely. Worth investigating any possible places where the application or session data could be cached in the serving infra. Perhaps also looking at timestamps of sessions of people experiencing these issues could indicate whether session data or credentials are being cached for users logged in around the same time.
 - Could it be at the code/application level? -- Possibly, but seemingly unlikely. Worth auditing the code to see if we are properly clearing session data at every possible opportunity.

If it is an IDCS / Postgres integration issue (this seems most likely and is worth further investigation):
 - Could it be that some users are being tied to the same identifier in the database when accounts are being created and merged? -- Possible, since multiple users saw a common user's name. We can find this out by querying the IDCS/Postgres identifiers for the affected users and seeing if there are any patterns / missing fields / similarities in their IDs. (Danielle did this above, and it seems not to be the case?). 
 - Could some state change in the IDCS database have reset some increment / counter / ID generator that has created collisions? -- There was some change in mid-late November with IDCS integration, around when the first incident was reported -- is it possible we are re-using IDs or components thereof, causing account ID collisions? Worth talking to Vinay at Seattle to understand the nature of this change/migration.
 - Is this affecting accounts created in a certain way as opposed to others? SSO vs. some other registration approach?
 - Also worth looking at account creation dates/times/sources.
 - Also worth looking at account metadata of the user whose info has appeared to others to understand if something went wrong in their account creation to cause them to be re-shown.

**Comment by rasmi** [comment] 2022-01-04 17:59
Some more details after our call this morning:
- Email addresses are not an appropriate unique identifier / primary key -- usernames are the only unique field, not emails.
- Sessions with IDCS/jwt must be appropriately closed by calling an endpoint, otherwise session credentials may persist in the application or in IDCS? -- Let's audit the code for how jwt data is or isn't being cleared. Is there anywhere else we may be inadvertently caching session credential data? 
- It is unclear if any actual form data was modified/edited across users as a result of this issue. If so, appropriate remediations must be taken.

**Closed** 2022-01-07 00:19 UTC
Labels: bug
