### ISSUE TITLE
Program Admin unable to view uploaded documents

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#2535] opened 2022-05-23 21:07 UTC
**Describe the bug**
One of the Program Admins for the Emergency Bill Assistance Program sees an error when she tries to download some of the documents that residents include in their application. I can ask the Program Admin for more information, but thought I'd see if this error message was an obvious one.

See attached for error message

**To Reproduce**
1. View email alert for a new application
2. Click on link within email to view the new application
3. Click to downloand the income documents

**Screenshots**
Attached

![civiform seattle gov page not found](https://user-images.githubusercontent.com/86082659/169906115-78866bc1-a1b2-477d-914a-1d9a00aacb6d.png)

**Comment by elisekalstad** [comment] 2022-05-23 21:08
With engineering team on 5/19-- discussed that the program numbers were different: document link has a program number of 638. The actual program number is 735. Not sure if that makes a difference though!

**Comment by shanemc-goog** [comment] 2022-05-23 22:30
FYI: The difference in program numbers likely indicates they had an application open with a previous revision (638) of the program.  Applicants with in-progress applications continue to complete that revision of the program if there are newer ones; 735 in this case I'd guess.

**Comment by kristinyim** [comment] 2022-05-26 20:03
Is this a duplicate of #2547?

**Comment by kristinyim** [comment] 2022-06-02 17:15
Going to close in favor of #2547

**Closed by kristinyim** 2022-06-02 17:15 UTC
Labels: bug, needs-triage
