### ISSUE TITLE
ORCA Card Form Error

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1678] opened 2021-11-09 01:37 UTC
**Describe the bug**
A resident received the following error message when clicking "NEXT" on form page 4 or 7 on the ORCA Middle School Form. (Page 4 is the Parent Enumerator question). ID: 7lj77i124.

**To Reproduce**
1. ORCA Middle School Opportunity form
2. I'm not sure if the parent "logged in" or continued with guest
3. Complete form pages 1-4
4. Select "Next" on page 4 and then see error

**Screenshots**
Attached
![ORCA card error](https://user-images.githubusercontent.com/86082659/140845750-5df223c0-4050-4157-8cf3-2135eb9f3107.JPG)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elisekalstad** [comment] 2021-11-10 21:19
Hi @dkatzz -- I submitted a ticket to John Doke to revise the access permissions. And Indira is available for 30 minutes today after 3:00 pm to do a screenshare, if you're available for a quick chat. (indira.alase@seattle.gov). Thank you!

**Comment by ettengererin** [comment] 2021-11-15 23:29
I located the error in the logs: 

`! @7lj77i124 - Internal server error, for (POST) [/applicants/3148/programs/356/blocks/13-0/false] ->`

The URL for the request makes sense -- the error happens on the 4th page of the ORCA card program (screen that asks for child's signature and date). '/false' is in the URL because the user didn't complete one or both fields and they clicked Next, so the expected behavior is to stay on the screen and notify the user of the error (i.e. this field is required).

No other insights from the logs yet...

**Comment by dkatzz** [comment] 2021-12-01 20:28
Thanks for looking into it @ettengererin !! I'm also seeing "play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.RuntimeException: java.time.format.DateTimeParseException: Text '11/08/21' could not be parsed at index 0]" - I tried to replicate and I'm not sure how they'd even enter a date without the format mm/dd/yyyy. @elisekalstad can you confirm others haven't mentioned this error? I think it may just be a weird one-off.

**Comment by elisekalstad** [comment] 2021-12-01 20:30
> Thanks for looking into it @ettengererin !! I'm also seeing "play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.RuntimeException: java.time.format.DateTimeParseException: Text '11/08/21' could not be parsed at index 0]" - I tried to replicate and I'm not sure how they'd even enter a date without the format mm/dd/yyyy. @elisekalstad can you confirm others haven't mentioned this error? I think it may just be a weird one-off.

I haven't heard of any other issues with this one. So maybe just a weird one-off?

**Comment by dkatzz** [comment] 2021-12-01 20:34
> > Thanks for looking into it @ettengererin !! I'm also seeing "play.api.UnexpectedException: Unexpected exception[CompletionException: java.lang.RuntimeException: java.time.format.DateTimeParseException: Text '11/08/21' could not be parsed at index 0]" - I tried to replicate and I'm not sure how they'd even enter a date without the format mm/dd/yyyy. @elisekalstad can you confirm others haven't mentioned this error? I think it may just be a weird one-off.
> 
> I haven't heard of any other issues with this one. So maybe just a weird one-off?

Sounds good!! I'll go ahead and close it cause we're unable to reproduce and we can open it back up if others have issues like this.

**Closed** 2021-12-01 20:34 UTC
Labels: bug
