### ISSUE TITLE
File not uploading in the "file upload question text section" 

### ISSUE THREAD

**Issue by ialv44** [seattle-uat/civiform#1428] opened 2021-06-22 18:41 UTC
**Is your feature request related to a problem? Please describe.**
While trying to upload file in the shiny new program, its gets uploaded but when you hit next, it takes you back to page 1. And if you hit review and check the "file upload question text section", the uploaded file cannot be seen.

**Describe the solution you'd like**
To be able to successfully upload the file and be seen in the review section post uploading.

**Additional context**
1. While uploading File
![image](https://user-images.githubusercontent.com/75772797/122980641-855e7200-d3b6-11eb-9909-2ca0f9f26b47.png)
2. After hitting next 
![image](https://user-images.githubusercontent.com/75772797/122980872-cd7d9480-d3b6-11eb-9e13-137239b0e7ee.png)
3. After hitting review
![image](https://user-images.githubusercontent.com/75772797/122980920-da9a8380-d3b6-11eb-90ff-6b412deb921b.png)

**Done when**
What conditions need to be met before this issue can be closed?

**Comment by neel-a-mehta** [comment] 2021-06-22 20:21
Thanks! A few questions:

- How large was this PDF file? 
- Does it work if you upload smaller PDFs?
- Does it work if you upload large PNGs or other image files?
- What happens if you upload Word docs or some random file type?

**Comment by ialv44** [comment] 2021-06-23 15:15
1. I tried with three PDF sizes: 25 kb, 56 kb & 1491kb
2.  It didn't work for either of the above PDF sizes
3. It didn't work with image files as well
4. Word and Excel files didn't work either.

**Comment by neel-a-mehta** [comment] 2021-06-24 01:10
Thanks! cc'ing @hmhsu in case he can figure out what's going on here.

**Comment by hmhsu** [comment] 2021-06-24 01:17
Hey @ialv44 thanks for reporting the issue! Have you tried clicking `-- FILE UPLOADED -- (click to download)` text and verified it is not downloading? Currently the file name is not retained after upload so you wouldn't be able to see the original file name.

**Comment by hmhsu** [comment] 2021-06-29 18:20
@ialv44 we've made quite a few improvements to file upload question in the last week. Now the uploaded file name is shown in both the file upload question screen and the review page. Closing this as I think the issue is sufficiently resolved. Feel free to open a new issue if you find additional things missing.

**Closed by hmhsu** 2021-06-29 18:20 UTC
Labels: bug
