### ISSUE TITLE
New options to questions are not saved

### ISSUE THREAD

**Issue by kristinyim** [seattle-uat/civiform#2013] opened 2022-03-02 21:15 UTC
After a CiviForm admin edits a question to have more options, whether that be adding options to a dropdown or a radio button, that selection is able to be chosen by the applicant initially but is not actually saved when the applicant goes to the review page or the admin exports the user data.

**Here's an example:**

1. The admin initially created a question "What is <$this> relationship to you?" with the following options: 
- Self
- Parent
- Child

2. They then added more options so the full option list is:
- Self
- Parent
- Child
- Grandparent
- Other

3. An applicant sees the question "What is <$this> relationship to you?" with the following options:
- Self
- Parent
- Child
- Grandparent
- Other

But if they select Grandparent, in the Review page it says that they selected Child. When the Admin exports the program responses, they also see Child as that applicant's response. The same goes for if they select Other, in the Review page and in the CSV export it shows them selecting Self.

**Workaround:**
Seattle is able to workaround this issue by instead of editing a question, deleting it altogether.

**Comment by shanemc-goog** [comment] 2022-03-02 22:14
Root cause of the issue seems to be that when you have a DropDown question, each time that you Make a new Version and add new options, their internal ID is set starting at 0.   The IDs need to be unique among all options, but this means each new Version with a new Option will add a new ID 0.

The below is after publishing a Question with Options 1 & 2, then creating a new version and adding Option 3.  Notice Option 3 ALSO has ID 0

Question
[
{**"id": 0**, "displayOrder": 0, "localizedOptionText": {"isRequ
ired": true, "translations": {"en_US": "Option 1"}}},

{"id": 1, "displayOrder": 1, "localizedOptionText": {"isRequired": true, "translations": {"en_US": "Option 2"}}},

{**"id": 0**, "displayOrder": 2, "localizedOptionText": {"isRequired": true, "translations": 
{"en_US": "Option 3"}}}

**Comment by shanemc-goog** [comment] 2022-03-02 22:21
An oddity here is that in the above data, when you view the application Block you see Option 3 which seems correct.

However if you repeat the above process and add Option 4, which will also have ID 0, then the Application block with show Option 4. 

Seemingly that view looks through the Options in reverse order.

**Comment by shanemc-goog** [comment] 2022-03-02 23:41
@elisekalstad Concretely for the existing Seattle deployment and data:

Any current Dropdown question that has been published with Options, then updated with new options is corrupted.  Fixing the core issue, won't correct the existing data.  So without subsequent work, the existing Questions are tainted and should not be used once a fix is deployed.

**Comment by elisekalstad** [comment] 2022-03-03 00:04
> @elisekalstad Concretely for the existing Seattle deployment and data:
> 
> Any current Dropdown question that has been published with Options, then updated with new options is corrupted. Fixing the core issue, won't correct the existing data.
> 
> So without subsequent clean up work, the existing Questions are tainted and should not be used even after a fix is deployed.

Thanks for the update, @shanemc-goog ! I can comb through an re-do any questions that have been updated with additional options.

**Comment by shanemc-goog** [comment] 2022-03-03 00:24
Ok!  And I'll just reiterate that basically no DropDown questions can simply be updated due to this bug.  Any additions of new Options requires that a completely new Question be created.

I think the fix for this is pretty straightforward so might be a good starter task for @gwendolyngoetz

**Comment by goldblatt** [comment] 2022-03-21 20:49
@zaralouis-sf is this done?

**Comment by zaralouis-sf** [comment] 2022-03-22 18:43
I have an open PR for it

**Closed** 2022-03-23 03:24 UTC
Labels: bug

**Comment by shanemc-goog** [comment] 2022-03-23 14:36
Verified in Staging.  I took a published Checkbox question that already existed, added new1 and new2 options to it, made a new program and was able to select those options and have it show in the summary

![image](https://user-images.githubusercontent.com/90928876/159724387-d5c33fc9-76cf-4fd6-b1ce-abab3bbd9bb0.png)

**Comment by elisekalstad** [comment] 2022-03-23 21:10
And I can verify that it's working in Production! Thank you!!

I tested the following:
1) Created a new radio question ("Test Question - Transportation Options") with options bike, car, bus
2) Started an application for the test program (https://civiform.seattle.gov/programs/test_delete)
3) Edited the radio question to include "taxi" as an option
4) Republished the form
5) Started an application for the test program (previous data was already saved). Selected "taxi" >> Next
6) Went to "Previous" and the "taxi" option was saved!

*Prior to the bug fix, it would have defaulted to bike and taxi would not have saved*

![image](https://user-images.githubusercontent.com/86082659/159796230-507826ea-0267-4042-83a5-b23c3e5f3ccf.png)
