### ISSUE TITLE
Radio question defaults for first option

### ISSUE THREAD

**Issue by elisekalstad** [seattle-uat/civiform#1675] opened 2021-11-06 01:15 UTC
**Describe the bug**
When families try to apply to the ORCA middle school opportunity program they are asked about their income. When families select the last option on the radio question for "Household income" >> "Not income eligible" the form saves it as the 1st option "Family size 2, annual income $32,000". I deleted the radio question options, saved, and re-published and the issues doesn't seem to be there anymore. But thought I'd add a bug in case this is something to look into a big more

**To Reproduce**
1. Go to "ORCA Middle School Opportunity"
2. Complete the question for household income "Not income eligible"
3. Select "Next"
4. Complete the rest of the form
5. Review the form as see that the answer to household income saved as "Family size 2, include $32,000"

**Screenshots**
Attached

**Additional context**
I deleted all answers and re-added them and don't see the issue any longer.
![Income default](https://user-images.githubusercontent.com/86082659/140592956-084d4b78-ea87-4bff-8af7-eb9d756224ef.png)

**Comment by ettengererin** [comment] 2021-11-09 18:54
I am unable to reproduce this bug -- let's keep a lookout to see if this keeps happening. Going to close this for now.

**Closed by ettengererin** 2021-11-09 18:54 UTC
Labels: bug

**Comment by elisekalstad** [comment] 2021-11-10 02:21
Thanks, Erin! I haven’t received any more emails about the issue.

[Title: City of Seattle logo]Elise Kalstad
She/Her/Hers
City of Seattle, Innovation & Performance
206-256-5515 | ***@***.******@***.***>
Learn more about Innovation & Performance: seattle.gov/innovation-performance<https://www.seattle.gov/innovation-performance>
