### ISSUE TITLE
Seed and document default questions

### ISSUE THREAD

**Issue by cassandralfernandes** [seattle-uat/civiform#1935] opened 2022-02-14 19:58 UTC
CiviForm application code assumes that there will be a question with question name "Name" and therefore the path applicant.name in order to display the applicant's name in the navigation header.

At the moment this requires the admin to manually create this question. We should seed the database with this question so it is guaranteed to be there for new deployments. We should also document this in both technical and user documentation.

See https://github.com/seattle-uat/civiform/blob/main/universal-application-tool-0.0.1/app/services/WellKnownPaths.java

**Comment by goldblatt** [comment] 2022-04-28 18:01
we need this for bloom deploy

**Comment by bion** [comment] 2022-06-02 22:19
closing this as a duplicate of https://github.com/seattle-uat/civiform/issues/2484

**Closed by bion** 2022-06-02 22:19 UTC
Labels: feature
