### ISSUE TITLE
Let Civiform admins specify questions/blocks as optional or required

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1001] opened 2021-05-05 20:55 UTC
I'm not sure if we've agreed whether or not questions/blocks should be optional or required by default. Either is fine as long as we're consistent. Going required by default may help reduce the chance of mistakes on the Civiform admins' part, though, since most questions will probably be required.

**Comment by kendrickt** [comment] 2021-05-18 20:44
related to #322

**Comment by lianne-oy** [comment] 2021-06-07 17:44
Should be a simple function - optional / required for just questions, not blocks.  Moving to icebox; will open new issue for questions only.

**Comment by kendrickt** [comment] 2021-06-07 17:48
This is a duplicate of #1307 for questions, and #322 for blocks. Closing this.

**Closed by kendrickt** 2021-06-07 17:48 UTC
Labels: story, user-feedback
