### ISSUE TITLE
File upload not working in staging

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#2728] opened 2022-06-15 05:06 UTC
After selecting a file and clicking "Upload" on the file upload questions, nothing happens (and the file is not uploaded). This has been the case today and yesterday in Azure staging.

**Comment by bion** [comment] 2022-06-15 05:22
duplicate of https://github.com/seattle-uat/civiform/issues/2728

**Closed by bion** 2022-06-15 05:22 UTC
Labels: bug, needs-triage
