### ISSUE TITLE
Add "+" button next to questions in the form builder

### ISSUE THREAD

**Issue by neel-a-mehta** [seattle-uat/civiform#1013] opened 2021-05-05 21:01 UTC
This will make it more obvious to the admin that they have to click it to add the question to the block. Right now there's no affordance for that.

**Comment by baipai** [comment] 2021-09-14 11:36
Hi, @elisekalstad, from the last feedback we got, you want to have the ability to edit questions in the program builder, which is to add the "+" button in the form builder. 

I want to double check if this is still the case?

<img width="291" alt="Screen Shot 2021-09-14 at 7 29 23 PM" src="https://user-images.githubusercontent.com/11348330/133250413-2aa5a488-5749-47e8-8bc6-010a30bd7fe3.png">

**Comment by shanemc-goog** [comment] 2021-09-21 17:46
Is this issue now a dupe of #1005 or is this different per the original text which wanted a visual indicator for clicking on questions in the side bar to add them to a program?

**Comment by leonwong** [comment] 2021-09-21 21:13
I believe #1005 is about letting people create new questions from the program application form design page. 

I believe this issue was originally about making it more obvious that you can add questions to the question bank to the form. The comment from baipai, however, is more relevant to #1005. 

I think we should keep the 2 issues separate, and we steer this one back to the original scope.

**Comment by baipai** [comment] 2021-09-23 15:41
Sorry for making the confusion here, and yes, my comment is closer to #1005. 

The reason I was trying to mention the question is because there is some conflict with adding the "+" button from the last form builder design(the one present to the city). So it is better to make the improvement based on the current staging design. (Was trying to add some record to let other people to follow, just in case the developing is start to apply the last design)

I am moving my comments into the #1005

**Closed** 2021-09-24 17:50 UTC
Labels: good first issue, story, UX, user-feedback
