### ISSUE TITLE
Add ability to create new questions to the Question Bank from the program creation flow

### ISSUE THREAD

**Issue by glorialiou** [seattle-uat/civiform#1930] opened 2022-02-13 17:50 UTC
Right now, if a CiviForm admin needs to create a new question, they have to jump between the Program tab/flow and Questions tab/flow, causing friction. Solution could be to have a plus button/create question button in the Program tab/flow. When a user clicks that, it takes them to a view where they are able to create a question, and after creation, returns them to the Program tab/flow screen they were previously on. The question then appears in the question bank for the user to use.

https://docs.google.com/presentation/d/1goxiepPXPrW3wK8wUSNoCpcf7iXIohXfj96iTYiQxo0/edit#slide=id.gf083eb9b36_0_1337

**Comment by baipai** [comment] 2022-02-14 09:31
Relate to #1005

**Comment by kristinyim** [comment] 2022-03-09 03:11
closing this as its a duplicate of #1005

**Closed by kristinyim** 2022-03-09 03:11 UTC
Labels: UX
